version: '3.7'

services:

  nginx:
    image: nginx:alpine
    ports:
     - "8080:8080"
    volumes:
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     - .:/var/www/vhosts/app
    working_dir: /var/www/vhosts/app
    depends_on:
      - "app"

  app:
     build: docker/app
     ports:
       - "9000:9000"
     volumes:
       - .:/var/www/vhosts/app
       - ./bin/migrations:/usr/local/bin/migrations
     working_dir: /var/www/vhosts/app
     environment:
       - ENV=development
       - API_KEY=49667D4B53178C27836C56A19EA38
     depends_on:
       - db

  db:
     image: postgres:10.2-alpine
     ports:
       - "5432:5432"
     volumes:
       - widget-data:/var/lib/postgresql/data
       - ./docker/postgresql:/docker-entrypoint-initdb.d
     environment:
       POSTGRES_USER: 'wally'
       POSTGRES_PASSWORD: password
       POSTGRES_DB: 'wallys'

volumes:
    widget-data: {}
